### PR TITLE
boolean keys do not get sanitised from the \n

### PR DESCRIPTION
**Pull request by zeph**
I would have loved to provide as well a patch... 
I'll try, but maybe someone else is faster than me

here is a unit test that properly isolates the problem

### CODE REVIEW

**Comment by zeph** [comment]
patch provided!!! :)

**Comment by Unknwon** [comment]
Just one comment and the conflict, otherwise LGTM.

**Comment by zeph** [comment]
@Unknwon rebased and fixed

**Comment by zeph** [comment]
@Unknwon is there anything else I need to provide? :)

**Comment by prawnsalad** [comment]
Will this be getting merged in? I'm getting hit with this issue :(

**Comment by zeph** [comment]
@prawnsalad seems it just got merged :) yay!

**Comment by prawnsalad** [comment]
Thanks!

**Pull request merged**
