### PR TITLE
Add support for Uint types

### PR DESCRIPTION
**Pull request by shore**
Any interest in supporting uint types?

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks a lot!

**Comment by shore** [comment]
I missed the key.In*() methods, do you want another pull request?
https://github.com/seastar-io/ini/commit/67da474c43f6586bb4dbc8358b58ea2a04042312

**Comment by Unknwon** [comment]
> I missed the key.In*() methods, do you want another pull request?

Do you mean test cases? I think I've pushed all missing tests :D

**Comment by shore** [comment]
No, in ini.go I missed:
func (k *Key) InUint((defaultVal uint, candidates []uint) uint) { // ... }
func (k *Key) InUint64(defaultVal uint64, candidates []uint64) uint64 { // ... }

**Comment by shore** [comment]
Ah, looks like both of my commits are already merged.  I opened the pull request before making my second commit, so I thought it wasn't included.  All looks good, thank you for your patience.

**Comment by Unknwon** [comment]
:trollface: no problem!

**Pull request merged**
