### PR TITLE
Escape delimiters in string slice values

### LINKED ISSUE #32: Parser should respect quoted or escaped delimiter
If we have a field defined as a slice and using space as a delimiter, say:

```
ExtraArgs   []string `ini:"extra_args" delim:" "`
```

An entry in the ini file formatted as:
```
extra_args = aaa bbb ccc
```

Correctly generates a slice of three string elements, "aaa", "bbb", and "ccc".

However, things get complicated if we need one of the elements to contain a space. I tried the following constructs without success:

```
extra_args = aaa "bbb and space" ccc

extra_args = aaa bbb\ and\ space ccc

extra_args = """
aaa
bbb and space
ccc"""
```

And neither seems to work.

Ideally, the delimiter shouldn't be matched inside quoted strings of it it's quoted with a backslash.

### PR DESCRIPTION
**Pull request by asciimoo**
Use backslash to escape delimiters.

Fixes #32

### CODE REVIEW

**Comment by Unknwon** [comment]
Thanks for the PR!

But the test cases didn't include the one proposed in https://github.com/go-ini/ini/issues/32, can you test on that and make sure it works?

**Comment by asciimoo** [comment]
> But the test cases didn't include the one proposed in #32, can you test on that and make sure it works?

Which test case isn't included?

**Comment by Unknwon** [comment]
Use space as delimiter and escape some spaces:

image

**Comment by asciimoo** [comment]
@Unknwon added in 840d413

**Pull request merged**
